---
# tasks file for ./roles/php-fpm

# - name: install / Import repository
#   get_url:
#     url: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
#     dest: /etc/yum.repos.d/remi.repo
#     mode: 0644

# - name: install / Install required packages
#   yum:
#     name: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
#     state: latest

- name: install / epel-release
  yum:
    name: epel-release
    state: present

- name: install / remi-release
  yum:
    name: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
    state: present

- name: install / Install required packages
  yum:
    name: "{{ item }}"
    state: present
    enablerepo: remi-php72
  with_items: "{{ php_packages }}"
